---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cron-restarter
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cron-restarter-role
rules:
  - apiGroups:
      - "*"
    resources:
      - deployments
      - statefulsets
      - leases
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - "*"
    resources:
      - cronjobs
      - endpoints
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cron-restarter-global
subjects:
- kind: ServiceAccount
  name: cron-restarter
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cron-restarter-role

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-restarter
  namespace: kube-system
  labels:
    app: cron-restarter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cron-restarter
  template:
    metadata:
      labels:
        app: cron-restarter
    spec:
      containers:
        - name: cron-restarter
          image: crazytaxii/kube-cron-restarter:latest
          command:
            - restarter
            - --leader-elect=true
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      serviceAccountName: cron-restarter
